name: SCA Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' # Specify the Python version to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Snyk
        run: npm install -g snyk
      - run: snyk auth db3c688c-9228-4473-afbf-be6a4686a2bc

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          # snyk test --json | jq '.vulnerabilities |= sort_by(.publicationTime) | .vulnerabilities |= reverse'
          # snyk test --json | snyk-to-html -o result.html
          snyk test --json-file-output=vuln.json

      - name: Upload Artifact GitHub Action in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: vuln.json
      - name: Upload Artifact GitHub Action in case of success
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: vuln.json
