name: SCA Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm i -g snyk
      - run: snyk auth db3c688c-9228-4473-afbf-be6a4686a2bc
      - run: snyk monitor

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          # snyk test --json | jq '.vulnerabilities |= sort_by(.publicationTime) | .vulnerabilities |= reverse'
          # snyk test --json | snyk-to-html -o result.html
          snyk test --json-file-output=vuln.json

      - name: Upload Artifact GitHub Action in case of failure
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: vuln.json
      - name: Upload Artifact GitHub Action in case of success
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: vuln.json
